### PR TITLE
Narrow the searched element type in `setHas` and `arrayIncludes`

### LINKED ISSUE #40: Proposal: better `arrayIncludes` and `setHas`
The current implementation doesn't work as expected if the array and the item are not the same general type.

```ts
const arr = [1, 2] as const;
const b: string = '3';
if (arrayIncludes(arr, b)) { // expected to complain but not
    // do sth
}
``` 

I propose adding a generic type for `arrayIncludes` and `setHas` to provide type checking for the `item`.

```ts
function arrayIncludes<Type extends TItem, TItem = unknown>(
	array: Type[] | readonly Type[],
	item: TItem,
	fromIndex?: number,
): item is Type {
	return array.includes(item as Type, fromIndex);
}

const arr = [1,2] as const;
const foo: number = 3;
const bar: string = '3';
if (arrayIncludes(arr, foo)) { // works
    // if the type guard return true, foo is 1 | 2 here
}

if (arrayIncludes(arr, bar)) { // Type 'number' is not assignable to type 'string'.(2345)
}
```

[Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwE6uQTwJKQDYgAmApgM4A8AKpgA7GLEAeUxYhpil2LAtgDSduxHogC8icAGswcAO5gAfAAoAUAEg0GTAC5OtYgG0AuogA+iVMWSEEeTHrrG+6mL11deztcFRweuEkYAfl0wEB4AI2JUZwBKXVdhRBgOajpEAG91SygQVCRNLAA6GHwiMiVEkWRU-QEfPwCmWIBuFQBfFRUIBFIoFHQxRAMARj4AJhMaxB6wPrbZvsQI3SkZeSHxtphgRCVCnDKSUn30AQjY2MyVRFvljpUdvc0So4qL2KA)

### PR DESCRIPTION
**Pull request by tychenjiajun**
fixes #40

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would you be able to include a type test?

**Comment by tychenjiajun** [comment]
Not sure how to write tests for this changes.

**Comment by sindresorhus** [comment]
Can't you assert the array afterwards to see if the type was narrowed?

**Comment by tychenjiajun** [comment]
I'll try

**Comment by tychenjiajun** [comment]
> Can't you assert the array afterwards to see if the type was narrowed?

I added `expectTypeOf`

**Pull request merged**
